"""
Oracle DDL Generator
Generates Oracle-specific DDL statements.
"""

from typing import List, Optional
from database.ddl.base import BaseDDL


class OracleDDL(BaseDDL):
    """Oracle-specific DDL generator"""
    
    db_type = "oracle"
    
    # ==========================================
    # Data Type Mappings
    # ==========================================
    
    def auto_increment_primary_key(self, name: str) -> str:
        """Generate NUMBER with sequence and trigger for auto-increment"""
        # Oracle 12c+ supports IDENTITY
        return f"NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    
    def text_type(self, length: Optional[int] = None) -> str:
        """Generate VARCHAR2 or CLOB type"""
        if length:
            return f"VARCHAR2({length} CHAR)"
        return "CLOB"
    
    def timestamp_type(self) -> str:
        """Generate TIMESTAMP type"""
        return "TIMESTAMP WITH TIME ZONE"
    
    def boolean_type(self) -> str:
        """Generate NUMBER(1) for boolean (Oracle doesn't have native boolean)"""
        return "NUMBER(1) DEFAULT 0"
    
    def json_type(self) -> str:
        """Generate CLOB for JSON (Oracle 12c+ has native JSON but CLOB is safer)"""
        return "CLOB"
    
    def blob_type(self) -> str:
        """Generate BLOB type"""
        return "BLOB"
    
    # ==========================================
    # Table Operations
    # ==========================================
    
    def create_table(self, table_name: str, columns: List[str], if_not_exists: bool = True) -> str:
        """Generate CREATE TABLE statement"""
        columns_sql = ",\n    ".join(columns)
        
        if if_not_exists:
            # Oracle doesn't support IF NOT EXISTS directly
            return f"""
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE {self.quote_identifier(table_name)} (\n    {columns_sql}\n)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
"""
        return f"CREATE TABLE {self.quote_identifier(table_name)} (\n    {columns_sql}\n)"
    
    def drop_table(self, table_name: str, if_exists: bool = True) -> str:
        """Generate DROP TABLE statement"""
        if if_exists:
            return f"""
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE {self.quote_identifier(table_name)} CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
"""
        return f"DROP TABLE {self.quote_identifier(table_name)} CASCADE CONSTRAINTS"
    
    def truncate_table(self, table_name: str) -> str:
        """Generate TRUNCATE TABLE statement"""
        return f"TRUNCATE TABLE {self.quote_identifier(table_name)}"
    
    # ==========================================
    # Index Operations
    # ==========================================
    
    def create_index(self, index_name: str, table_name: str, columns: List[str], 
                     unique: bool = False, if_not_exists: bool = True) -> str:
        """Generate CREATE INDEX statement"""
        unique_sql = "UNIQUE " if unique else ""
        columns_sql = ", ".join([self.quote_identifier(c) for c in columns])
        
        if if_not_exists:
            return f"""
BEGIN
    EXECUTE IMMEDIATE 'CREATE {unique_sql}INDEX {index_name} ON {self.quote_identifier(table_name)} ({columns_sql})';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
"""
        return f"CREATE {unique_sql}INDEX {index_name} ON {self.quote_identifier(table_name)} ({columns_sql})"
    
    def drop_index(self, index_name: str, table_name: Optional[str] = None) -> str:
        """Generate DROP INDEX statement"""
        return f"DROP INDEX {index_name}"
    
    # ==========================================
    # Column Operations
    # ==========================================
    
    def add_column(self, table_name: str, column_name: str, column_type: str, 
                   default_value: Optional[str] = None) -> str:
        """Generate ALTER TABLE ADD COLUMN statement"""
        default_sql = f" DEFAULT {default_value}" if default_value else ""
        
        return f"""
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE {self.quote_identifier(table_name)} ADD ({self.quote_identifier(column_name)} {column_type}{default_sql})';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN  -- Column already exists
            RAISE;
        END IF;
END;
"""
    
    def drop_column(self, table_name: str, column_name: str) -> str:
        """Generate ALTER TABLE DROP COLUMN statement"""
        return f"ALTER TABLE {self.quote_identifier(table_name)} DROP COLUMN {self.quote_identifier(column_name)}"
    
    def column_exists(self, table_name: str, column_name: str) -> str:
        """Generate SQL to check if column exists"""
        return f"""
SELECT column_name 
FROM user_tab_columns 
WHERE table_name = UPPER('{table_name}') AND column_name = UPPER('{column_name}')
"""
    
    # ==========================================
    # Upsert Operations
    # ==========================================
    
    def upsert(self, table_name: str, columns: List[str], 
               conflict_columns: List[str], update_columns: Optional[List[str]] = None) -> str:
        """Generate MERGE statement for Oracle"""
        columns_sql = ", ".join([self.quote_identifier(c) for c in columns])
        placeholders = ", ".join([self.placeholder(c) for c in columns])
        
        if update_columns is None:
            update_columns = [c for c in columns if c not in conflict_columns]
        
        # Build ON clause for conflict columns
        on_clause = " AND ".join([f"t.{self.quote_identifier(c)} = s.{self.quote_identifier(c)}" for c in conflict_columns])
        
        # Build UPDATE SET clause
        update_sql = ", ".join([f"t.{self.quote_identifier(c)} = s.{self.quote_identifier(c)}" for c in update_columns])
        
        return f"""
MERGE INTO {self.quote_identifier(table_name)} t
USING (
    SELECT {placeholders} FROM dual
) s ON ({on_clause})
WHEN MATCHED THEN
    UPDATE SET {update_sql}
WHEN NOT MATCHED THEN
    INSERT ({columns_sql}) VALUES ({placeholders})
"""
    
    # ==========================================
    # Utility Methods
    # ==========================================
    
    def quote_identifier(self, identifier: str) -> str:
        """Quote an identifier with double quotes (Oracle style)"""
        return f'"{identifier.upper()}"'
